# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, atlas, f77blas, feast, gfortran, globalLock, hmatrix
, hspec, lapack, primitive, QuickCheck, sparseLinear, suitesparse
, vector
}:

cabal.mkDerivation (self: {
  pname = "feast";
  version = "0.1.0.0";
  src = ./.;
  buildDepends = [
    globalLock hmatrix primitive sparseLinear suitesparse vector
  ];
  testDepends = [ hspec QuickCheck sparseLinear suitesparse vector ];
  extraLibraries = [ atlas f77blas feast gfortran lapack ];
  meta = {
    description = "Haskell bindings to the FEAST eigensolver library";
    license = self.stdenv.lib.licenses.gpl2;
    platforms = self.ghc.meta.platforms;
  };
})
