on: [push, pull_request]
name: Test
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['latest', '8.10']
    steps:
      - run: sudo apt install -y libblas-dev liblapack-dev
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal build sparse-linear